# .golangci.toml
#:schema https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version = "2"

# Exclude checking errors from defer functions
[[linters.exclusions.rules]]
linters = [ "errcheck" ]
source = "^\\s*defer\\s+"
